a=input("enter the value")
print(type(a))
i=int(a)
print(type(i))
i=input("enter float value")
print(type(i))
j=float(i)
print(type(j))
p=input("enter complex value")
print(type(p))
q=complex(p)
print(type(q))
x=input("enter bool value")
print(type(x))
y=bool(x)
print(type(y))
